"""Removed created date

Revision ID: 2cc9fc958e70
Revises: 560587ca3673
Create Date: 2015-11-21 17:21:14.330378

"""

# revision identifiers, used by Alembic.
revision = '2cc9fc958e70'
down_revision = '560587ca3673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    ### end Alembic commands ###
