"""Removed Unique Index for item name

Revision ID: 3f0031f6af80
Revises: 460e38b77a6e
Create Date: 2015-11-25 04:28:28.620968

"""

# revision identifiers, used by Alembic.
revision = '3f0031f6af80'
down_revision = '460e38b77a6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'items_name_key', 'items', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'items_name_key', 'items', ['name'])
    ### end Alembic commands ###
