"""Added Category Index

Revision ID: 460e38b77a6e
Revises: 5593bbce718f
Create Date: 2015-11-23 11:00:08.284138

"""

# revision identifiers, used by Alembic.
revision = '460e38b77a6e'
down_revision = '5593bbce718f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    ### end Alembic commands ###
