"""Added timestamp

Revision ID: 5593bbce718f
Revises: 15cf1b41d729
Create Date: 2015-11-23 10:29:37.446579

"""

# revision identifiers, used by Alembic.
revision = '5593bbce718f'
down_revision = '15cf1b41d729'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'timestamp')
    ### end Alembic commands ###
