"""Renamed Categories table

Revision ID: 8e45f78b8d0
Revises: 15d7bbe87005
Create Date: 2015-11-21 03:26:28.308503

"""

# revision identifiers, used by Alembic.
revision = '8e45f78b8d0'
down_revision = '15d7bbe87005'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table(u'categories')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'categories',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'categories_pkey')
    )
    op.drop_table('category')
    ### end Alembic commands ###
